## Quiz 01 - Computer vision

## EJECUTA ESTA CELDA PARA AUTENTICARTE CON TU CUENTA DE GMAIL

In [ ]:
from mooclib import *
import inspect, urllib
html, auth_code, userinfo = google_authenticate(PORT_NUMBER=8080)
html

## <font style="color: red"> Este quiz tiene cuatro ejercicios<!-- ONLY IN NOTEBOOK -->

### Ejercicio 1: Preprocesamiento de imágenes

Completa la función `preprocess_image` para que:

1. Lea la imagen `imgs/puente.jpg`. Es una imagen de 300x450 con tres canales de color
- Convierta la imagen en escala de grises calculando la intensidad de gris de cada pixel como el promedio de los valores del propio pixel en los tres canales (usa `numpy.mean`)
- Realice una convolución con el siguiente filtro

      [[ 0 -1  0]
       [-1  5 -1] 
       [ 0 -1  0]]
 
- Saque el valor absoluto de cada pixel (usa `numpy.abs`)

El resultado debe de ser una imagen de tamaño 298x448

Importa dentro de la función las librerías que necesites para implementarla.

Si necesitas definir una función auxiliar (p.ej. para hacer la convolución), hazlo dentro de la misma función. P.ej.:

     def preprocess_image():
         from skimage import io
         img = io.imread("img/puente.jpg")
         gray_img = ... # convertir a escala de grises
         
         def convolution (A,f):
            cols = A.shape[0]-f.shape[0]+1
            rows = A.shape[1]-f.shape[1]+1
            ...  # otro codigo
            return result
            
         f = ... # el filtro de convolucion
         cimg = convolution(gray_img,f)
         ... # otro codigo
         return result_img

La imagen resultado debería de verse así
<img src="imgs/puente-result.jpg"/>

Si sumas el valor de los pixeles de la imagen resultado debe de dar 18800487

In [ ]:
def preprocess_image():
    import numpy as np
    from skimage import io
    import numpy as np
    
    ## TU CODIGO AQUI
    result_img = ....
    
    return result_img

import urllib, inspect
src1 = urllib.quote_plus(inspect.getsource(preprocess_image))

Verifica visualmente si tu imagen resultado parece correcta

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline
cimg = preprocess_image()
plt.imshow(cimg, cmap=plt.cm.Greys_r, interpolation="none");
print cimg.shape, np.sum(cimg)

#### check your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION QZ1_1 $src1

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION QZ1_1 $src1

### Ejercicio 2: Clasificación con K-Neighbors

Completa la función siguiente para que:

1. Cargue el fichero `data/mnist1.5k.csv` según usado en las notas del curso
2. Construya un modelo predictivo con el algoritmo de `KNeighborsClassifier` [[ref](http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html)] usando un valor de 3 para el parámetro `n_neighbors` y entrenando con los últimos 1000 elementos de MNIST (los elementos del 500 en adelante)
3. Devuelva el modelo construído.

Si pruebas el modelo generado con los primeros 500 elementos debe de dar un desempeño del 87.4%

In [ ]:
def mnist_kmodel():

    from sklearn.neighbors import KNeighborsClassifier 
    import numpy as np

    # TU CODIGO AQUI
    model = ...
    
    return model

import urllib, inspect
src2 = urllib.quote_plus(inspect.getsource(mnist_kmodel))

#### check your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION QZ1_2 $src2

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION QZ1_2 $src2

### Ejercicio 3: Clasificación con SVD + KNeighbors

Completa la función siguiente para que haga lo mismo que la del ejercicio anterior, pero que realice un `SVD` de 60 componentes ANTES de extraer los datos de entrenamiento y de entrenar el modelo. Fíjate que en las Notas 02C se usa un SVC con 100 componentes.

Usa igualmente los últimos 1000 elementos para entrenar y un KNeighborsClassifier con `n_neighbors`=3.

La función ha de devolver el modelo entrenado.

Si pruebas tu modelo con los primeros 500 elementos el desempeño debería de ser del 82.2%.

In [ ]:
def mnist_svdk():
    import scipy.linalg as la
    import numpy as np
    from sklearn.neighbors import KNeighborsClassifier 

    # TU CODIGO AQUI
    model = ...
        
    return model

import urllib, inspect
src3 = urllib.quote_plus(inspect.getsource(mnist_svdk))

#### check your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION QZ1_3 $src3

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION QZ1_3 $src3

### Ejercicio 4: Mejor clasificación con KNeighbours

Repite el ejercicio 2, pero esta vez usa el valor de `n_neighbors` entre 1 y 10 (ambos incluidos) que dé el mejor resultado en test (los primeros 500 elementos), después de haber entrenado con los últimos 1000 elementos.

La función siguiente ha de devolver un modelo configurado con el valor de `n_neighbors` óptimo.

_Sugerencia_: Usa otro notebook para probar los distintos valores de `n_neighbors` y luego completa la función siguiente usando el valor óptimo.

Usando el valor óptimo debes de obtener un desempeño de 89.2% con los primeros 500 datos.

In [ ]:
def best_mnist():
    from sklearn.neighbors import KNeighborsClassifier 
    import numpy as np
    
    # TU CODIGO AQUI
    model = ...
    
    return model

import urllib, inspect
src4 = urllib.quote_plus(inspect.getsource(best_mnist))

#### check your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION QZ1_4 $src4

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION QZ1_4 $src4